name: CI Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TAG: latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/release
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}